[package]
name = "bsuppla"
version = "0.1.0"
edition = "2024"

[dependencies]
tar = "0.4"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
goblin = "0.8"
walkdir = "2.5"
clap = { version = "4.5", features = ["derive"] }
